[tool.poetry]
name = "pysh"
version = "0.1d"
description = "A shell mixing Python and Bash syntax"
authors = ["Antoine d'Otreppe <a.dotreppe@aspyct.org>"]
license = "MIT"
readme = "README.rst"
homepage = "http://www.github.com/aspyct/pysh"
repository = "http://www.github.com/aspyct/pysh"

[tool.poetry.dependencies]
python = ">=3.6"

[tool.poetry.scripts]
pysh = "pysh.cli:main"

[build-system]
requires = ["poetry-core>=1.5.0"]
build-backend = "poetry.core.masonry.api"
